name: Generate and Commit Excel

on:
  workflow_dispatch:
    inputs:
      startDay:
        description: "Start day in YYYY-MM-DD format"
        required: true
        default: "2024-12-26"
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    # Grant write permission to commit/push changes
    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          # Ensures the default token is not left in local git config
          persist-credentials: true

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Build
        run: go build -o hormones hrtfunct.go

      - name: Run the generator
        run: |
           # Use the 'startDay' input from the workflow_dispatch event
           ./hormones --start-day=${{ github.event.inputs.startDay }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "[email protected]"
          # Stage only the spreadsheet file (or anything else you want to commit)
          git add HormonesSchedule.xlsx
          # Commit changes; if there are no changes, '|| echo' avoids a fatal error
          git commit -m "Auto-generated Excel for date: ${{ github.event.inputs.startDay }}" || echo "No changes to commit"
          git push
